const books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Fiction",
    year: 1925,
    price: 10.99,
    rating: 4.5,
    description: "A novel set in the 1920s that explores themes of wealth, love, and the American Dream.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/The_Great_Gatsby_Cover_1925_Retouched.jpg/500px-The_Great_Gatsby_Cover_1925_Retouched.jpg",
  },
  {
    id: 2,
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-Improvement",
    year: 2018,
    price: 12.99,
    rating: 4.8,
    description: "A guide to building good habits and breaking bad ones with practical strategies.",
    image: "../img/atomic-habits.jpg",
  },
  {
    id: 3,
    title: "Clean Code",
    author: "Robert C. Martin",
    genre: "Programming",
    year: 2008,
    price: 29.99,
    rating: 4.7,
    description: "A handbook of agile software craftsmanship that teaches how to write clean, maintainable code.",
    image: "https://m.media-amazon.com/images/I/51E2055ZGUL.jpg",
  },
  {
    id: 4,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Fiction",
    year: 1960,
    price: 14.99,
    rating: 4.9,
    description: "A story of racial injustice and moral growth in the American South.",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg/1200px-To_Kill_a_Mockingbird_%28first_edition_cover%29.jpg",
  },
  {
    id: 5,
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen R. Covey",
    genre: "Motivation",
    year: 1989,
    price: 15.99,
    rating: 4.6,
    description: "Principles for personal and professional effectiveness.",
    image: "https://d28hgpri8am2if.cloudfront.net/book_images/onix/cvr9781982137137/the-7-habits-of-highly-effective-people-9781982137137_hr.jpg",
  },
  {
    id: 6,
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    genre: "Programming",
    year: 1999,
    price: 34.99,
    rating: 4.8,
    description: "Tips and practices for becoming a better, more pragmatic software developer.",
    image: "https://m.media-amazon.com/images/I/61ztlXgCmpL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 7,
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Motivation",
    year: 1988,
    price: 9.99,
    rating: 4.7,
    description: "A philosophical novel about pursuing your dreams.",
    image: "https://m.media-amazon.com/images/I/81FPzmB5fgL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 8,
    title: "Deep Work",
    author: "Cal Newport",
    genre: "Self-Improvement",
    year: 2016,
    price: 18.99,
    rating: 4.5,
    description: "A book on how to focus without distraction in a world full of noise.",
    image: "https://m.media-amazon.com/images/I/81JJ7fyyKyS.jpg",
  },
  {
    id: 9,
    title: "You Don’t Know JS",
    author: "Kyle Simpson",
    genre: "Programming",
    year: 2014,
    price: 24.99,
    rating: 4.6,
    description: "A deep dive into the mechanics of JavaScript.",
    image: "https://img.drz.lazcdn.com/static/bd/p/9b2b313193f3fc16a13dc8986a439c87.jpg_720x720q80.jpg",
  },
  {
    id: 10,
    title: "Dune",
    author: "Frank Herbert",
    genre: "Science Fiction",
    year: 1965,
    price: 22.99,
    rating: 4.8,
    description: "A science fiction saga of politics, religion, and power on the desert planet Arrakis.",
    image: "https://librairiesaga.ca/cdn/shop/products/BNCImageAPI_733ddddf-e83e-4cb8-9f42-e549d3121eda_600x600_crop_center.jpg?v=1636351617",
  },
  {
    id: 11,
    title: "The Power of Now",
    author: "Eckhart Tolle",
    genre: "Self-Improvement",
    year: 1997,
    price: 16.99,
    rating: 4.7,
    description: "Spiritual guidance on living in the present moment.",
    image: "https://m.media-amazon.com/images/I/61Ij8nLooNL.jpg",
  },
  {
    id: 12,
    title: "Ikigai",
    author: "Héctor García, Francesc Miralles",
    genre: "Motivation",
    year: 2016,
    price: 14.99,
    rating: 4.5,
    description: "A Japanese concept about finding joy, purpose, and meaning in daily life.",
    image: "https://pembangunansosial.fisipol.ugm.ac.id/wp-content/uploads/sites/61/2021/12/ikigai.jpg",
  },
  {
    id: 13,
    title: "1984",
    author: "George Orwell",
    genre: "Fiction",
    year: 1949,
    price: 12.99,
    rating: 4.8,
    description: "A dystopian novel about totalitarianism, surveillance, and truth.",
    image: "https://m.media-amazon.com/images/I/61NAx5pd6XL._AC_UF1000,1000_QL80_.jpg",
  },
  {
    id: 14,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    genre: "Self-Improvement",
    year: 2016,
    price: 15.99,
    rating: 4.6,
    description: "A no-nonsense approach to living a better life by focusing on what matters.",
    image: "https://ebooks.gramedia.com/ebook-covers/34319/image_highres/ID_HCO2016MTH09TSAONGAF.jpeg",
  },
  {
    id: 15,
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    genre: "Fantasy",
    year: 1997,
    price: 19.99,
    rating: 4.9,
    description: "A young wizard's journey begins at Hogwarts School of Witchcraft and Wizardry.",
    image: "https://upload.wikimedia.org/wikipedia/id/b/bf/Harry_Potter_and_the_Sorcerer%27s_Stone.jpg",
  },
];

export default books;
